All environment variables available to firebase.ts: 228-6b17fd919fe2fafc.js:1:15209 [firebase.ts] Value of process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID before use: allobudget 228-6b17fd919fe2fafc.js:1:15360 [firebase.ts] Attempting to initialize Firebase with projectId from firebaseConfig: allobudget 228-6b17fd919fe2fafc.js:1:15712 [firebase.ts] Attempting to initialize Firebase with apiKey from firebaseConfig: ******** 228-6b17fd919fe2fafc.js:1:15823 [firebase.ts] firebaseConfig object constructed: {"apiKey":"********","authDomain":"allobudget.firebaseapp.com","projectId":"allobudget","storageBucket":"allobudget.appspot.com","messagingSenderId":"609455213437","appId":"1:609455213437:web:d5c02301bc857082509a14"} 228-6b17fd919fe2fafc.js:1:15946 Firebase initialized successfully in firebase.ts (new app instance). Project ID from SDK after init: allobudget 228-6b17fd919fe2fafc.js:1:16757 AppContext: Starting data fetch for user 3ll8Y9BJkFeGFl3nVpBxtnEVm8q2... 228-6b17fd919fe2fafc.js:1:1755 AppContext: Data fetching successful for user 3ll8Y9BJkFeGFl3nVpBxtnEVm8q2. 228-6b17fd919fe2fafc.js:1:3681 The resource at “https://allobudget--allobudget.us-central1.hosted.app/_next/static/media/93f479601ee12b01-s.p.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dashboard [EditEnvelopeForm] budgetAmount field.value: 0 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] Envelope prop received: {"id":"T6Gcc0Ml3u398PV18mnD","category":"Frequent Expenses","orderIndex":3,"name":"Convenience","budgetAmount":0,"createdAt":"2025-05-14T00:00:00-06:00","userId":"3ll8Y9BJkFeGFl3nVpBxtnEVm8q2"} 101-0d0122377f319191.js:1:1486 [EditEnvelopeForm] Initializing form with budgetAmount: 0 101-0d0122377f319191.js:1:1648 [EditEnvelopeForm] budgetAmount field.value: 0 2 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] budgetAmount field.value: 0 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] budgetAmount field.value: 2 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] budgetAmount field.value: 23 2 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] budgetAmount field.value: 23.03 3 101-0d0122377f319191.js:1:2618 [EditEnvelopeForm] Submitting values: {"name":"Convenience","budgetAmount":23.03,"category":"Frequent Expenses"} 101-0d0122377f319191.js:1:1925 Error updating envelope: FirebaseError: Function updateDoc() called with invalid data. Unsupported field value: undefined (found in field estimatedAmount in document users/3ll8Y9BJkFeGFl3nVpBxtnEVm8q2/envelopes/T6Gcc0Ml3u398PV18mnD)     NextJS 46 684-b4e3f3d39e0dabe3.js:1:107914 [EditEnvelopeForm] budgetAmount field.value: 23.03 2 101-0d0122377f319191.js:1:2618
​